### ISSUE TITLE
关于迁移Dva项目到typescript有感 这篇文章

### ISSUE THREAD

**Issue by flyFatSeal** [southerncross/blog#31]
能否贴一下完整得代码呢 刚好项目也遇到了同样得问题 想参考一下

**Comment by southerncross** [comment]
@flyFatSeal 嗯好的，我这几天整理一下发一个npm包出来，也方便引用

**Comment by flyFatSeal** [comment]
> @flyFatSeal 嗯好的，我这几天整理一下发一个npm包出来，也方便引用

太感谢了！

**Comment by flyFatSeal** [comment]
大大 不好意思又打扰了 之前参考你得方式写出了类似得效果 但是 在推导payload是否存在 遇到麻烦了  不知道能不能参考下对应得代码 期待学习一下

**Comment by southerncross** [comment]
实在抱歉最近太忙没顾得上，我这周末弄一下 😣

**Comment by southerncross** [comment]
@flyFatSeal https://github.com/Moka-FE/dva-types 更新在这里了 😅

**Comment by flyFatSeal** [comment]
> @flyFatSeal https://github.com/Moka-FE/dva-types 更新在这里了 😅

感谢大大！
